import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
const server = spawn('node', ['tools/serve.mjs', '.', '8155'], { stdio: 'ignore' });
await new Promise(r => setTimeout(r, 800));
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 1340, height: 1000 } });
await p.goto('http://127.0.0.1:8155/gm/index.html'); await p.waitForTimeout(300);
await p.getByRole('button', { name: 'Just roll one', exact: true }).click(); await p.waitForTimeout(400);
await p.getByRole('button', { name: 'Roster', exact: true }).click(); await p.waitForTimeout(200);
await p.locator('button.wlink').first().click(); await p.waitForTimeout(300);
const t = await p.locator('.card').innerText();
for (const line of t.split('\n')) if (/NaN|undefined|\[object/i.test(line)) console.log('BAD LINE:', JSON.stringify(line));
await b.close(); server.kill();
