#!/usr/bin/env python3
"""Generate js/data/nfl-history.js from nflverse season player stats.

The app is otherwise self-contained and deterministic, so historical seasons are
baked in rather than fetched at runtime. Source:

    https://github.com/nflverse/nflverse-data/releases/download/player_stats/
        player_stats_season_<YEAR>.csv

Regular season only. PPR is nflverse's fantasy_points_ppr (1 per reception,
4-point passing touchdowns), which is the same scoring the app ships as its
default, so the numbers are comparable to what the league produces.

Usage:  python3 tools/build-history.py 2019 2020 2021 2022 2023 2024
        (expects the CSVs already downloaded to /tmp/ps<YEAR>.csv, or pass
         --fetch to pull them)
"""
import csv, os, re, subprocess, sys

TOP_PER_POS = 40
POSITIONS = ('QB', 'RB', 'WR', 'TE')
URL = ('https://github.com/nflverse/nflverse-data/releases/download/'
       'player_stats/player_stats_season_%d.csv')
OUT = os.path.join(os.path.dirname(__file__), '..', 'js', 'data', 'nfl-history.js')
PLAYERS = os.path.join(os.path.dirname(__file__), '..', 'js', 'data', 'nfl-players.js')


def current_ids():
    """display name -> current player id, so a face and a profile still resolve."""
    src = open(PLAYERS, encoding='utf-8').read()
    body = re.search(r'NFL_SRC=`(.*?)`', src, re.S).group(1)
    out = {}
    for line in body.strip().split('\n'):
        f = line.split('|')
        if len(f) > 2:
            out.setdefault(f[2].strip(), f[0].strip())
    return out


def season_rows(year, fetch):
    path = '/tmp/ps%d.csv' % year
    if fetch or not os.path.exists(path):
        subprocess.run(['curl', '-sSL', '-o', path, URL % year], check=True)
    rows = [r for r in csv.DictReader(open(path, encoding='utf-8'))
            if r['season_type'] == 'REG' and r['position'] in POSITIONS]
    out = []
    for pos in POSITIONS:
        group = [r for r in rows if r['position'] == pos]
        group.sort(key=lambda r: -float(r['fantasy_points_ppr'] or 0))
        out += group[:TOP_PER_POS]
    out.sort(key=lambda r: -float(r['fantasy_points_ppr'] or 0))
    return out


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('-')]
    fetch = '--fetch' in sys.argv
    years = sorted({int(a) for a in args}, reverse=True)
    ids = current_ids()

    blocks, matched, total = [], 0, 0
    for y in years:
        lines = []
        for r in season_rows(y, fetch):
            name = r['player_display_name'].replace('|', '')
            pid = ids.get(name, '')
            if pid:
                matched += 1
            total += 1
            lines.append('|'.join([
                name, r['position'], r['recent_team'], str(int(float(r['games']))),
                '%.1f' % float(r['fantasy_points_ppr'] or 0),
                '%.1f' % float(r['fantasy_points'] or 0),
                pid,
            ]))
        blocks.append('  %d: `%s`,' % (y, '\n'.join(lines)))

    js = '''// Real NFL production from completed seasons, for the Leaders rail.
//
// Generated by tools/build-history.py from nflverse season player stats
// (github.com/nflverse/nflverse-data), regular season only. Do not hand-edit -
// re-run the script instead.
//
// PPR here is nflverse's fantasy_points_ppr: 1 point per reception, 4 points per
// passing touchdown, 0.04 per passing yard, 0.1 per rushing/receiving yard. That
// is the same scoring this app ships as its default, so a historical total is
// directly comparable to what the league puts up.
//
// Top %d at each of QB, RB, WR and TE per season. `id` is this player's current
// player id where they are still on a roster, so their face and profile still
// open; it is blank for anyone who has since retired.
//
// name|pos|team|games|ppr|standard|id
export const HIST_SEASONS = [%s];
export const HIST_SRC = {
%s
};

const parsed = {};
/** [{name,pos,tm,g,ppr,std,id,ppg}] for one season, best PPR first. */
export function histSeason(year) {
  if (parsed[year]) return parsed[year];
  const src = HIST_SRC[year];
  if (!src) return [];
  parsed[year] = src.trim().split('\\n').map(line => {
    const f = line.split('|');
    const ppr = +f[4], g = +f[3];
    return { name: f[0], pos: f[1], tm: f[2], g, ppr, std: +f[5], id: f[6] || null,
             ppg: g ? Math.round((ppr / g) * 10) / 10 : 0 };
  });
  return parsed[year];
}

/** One season filtered to a position ('ALL' for every position). */
export function histLeaders(year, pos) {
  const rows = histSeason(year);
  return (!pos || pos === 'ALL') ? rows : rows.filter(r => r.pos === pos);
}
''' % (TOP_PER_POS, ', '.join(str(y) for y in years), '\n'.join(blocks))

    open(OUT, 'w', encoding='utf-8').write(js)
    print('%s: %d seasons, %d rows, %d matched to a current player (%.0f%%)'
          % (os.path.relpath(OUT), len(years), total, matched, 100.0 * matched / total))


if __name__ == '__main__':
    main()
