import { chromium } from 'playwright';
import fs from 'fs';
const R = new URL('./fixtures/', import.meta.url).pathname;
const OUT = process.argv[2] || '.';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 3 });
const errs = [], hits = {};
p.on('pageerror', e => errs.push(String(e)));
const json = (r, f) => r.fulfill({ status: 200, contentType: 'application/json', body: f && fs.existsSync(f) ? fs.readFileSync(f) : '[]', headers: { 'access-control-allow-origin': '*' } });
await p.route('**', r => {
  const u = new URL(r.request().url());
  if (u.protocol === 'file:') return r.continue();
  if (u.hostname === 'api.sleeper.app') {
    hits[u.pathname] = (hits[u.pathname] || 0) + 1;
    const m = u.pathname.match(/^\/v1\/league\/(\d+)(?:\/(\w+)(?:\/(\d+))?)?$/);
    if (!m || m[1] !== '1312045587541020672') return r.fulfill({ status: 404, body: 'null' });
    const f = !m[2] ? 'league.json' : m[2] === 'matchups' ? `matchups_${m[3]}.json` : m[2] + '.json';
    return json(r, R + 'league/' + f);
  }
  if (u.hostname === 'api.sleeper.com') { const m = u.pathname.match(/\/(stats|projections)\/nfl\/2026\/(\d+)/); return json(r, m && R + 'live/' + (m[1] === 'stats' ? 'stats_' : 'proj_') + m[2] + '.json'); }
  if (u.hostname === 'site.api.espn.com') return json(r, R + 'live/' + (u.pathname.endsWith('/scoreboard') ? 'board_' + u.searchParams.get('week') : 'summary_' + u.searchParams.get('event')) + '.json');
  return r.abort();
});
await p.goto('file://' + new URL('../1stPrototype.html', import.meta.url).pathname, { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(800);
const ok = (l, c, x) => console.log((c ? '  ok   ' : '  FAIL ') + l + (x ? '  ' + x : ''));
await p.locator('.hb-new', { hasText: 'Import from Sleeper' }).click();
await p.fill('#slId', '1312045587541020672');
await p.locator('#slFindBtn').click();
await p.waitForSelector('.sl-team');
await p.screenshot({ path: OUT + '/S1-pick-team.png' });
const list = await p.locator('.sl-team b').allInnerTexts();
ok('10 teams offered', list.length === 10, list.join(' | '));
await p.locator('.sl-team', { hasText: 'Jumpin' }).click();
await p.waitForFunction(`lvState().at > 0 && document.querySelector('.league-id .nm') && /City Boys/.test(document.querySelector('.league-id .nm').textContent)`, null, { timeout: 20000 }).catch(() => {});
await p.waitForTimeout(2500);
const st = await p.evaluate(`(() => { const s = lvState(); const r = myLeagues().find(l => l.sleeper); return { s, name: r && r.name, teams: r && r.teams.map(t => t.n + ' ' + t.rec), me: r && r.teams[0].n, slots: r && r.slots, weeks: r && Object.keys(r.sleeper.pts || {}) }; })()`);
console.log(JSON.stringify(st));
ok('league imported as City Boys Dynasty', st.name === 'City Boys Dynasty');
ok('my team is Jumpin\' Uncs', /Jumpin/.test(st.me));
ok('records from Sleeper', st.teams.some(t => /\d+-\d+/.test(t) && !/ 0-0$/.test(t)));
ok('roster spots from Sleeper (2 FLEX, 1 SUPERFLEX, 15 bench, 5 taxi, 3 IR)', st.slots.FLEX === 2 && st.slots.SFLX === 1 && st.slots.bench === 15 && st.slots.taxi === 5 && st.slots.ir === 3, JSON.stringify(st.slots));
const raw = w => JSON.parse(fs.readFileSync(R + `league/matchups_${w}.json`));
const games = await p.evaluate(`[1,2,3,4].map(w => getGames(w).map(g => [g.a, g.as, g.x, g.xs]))`);
let allMatch = true;
[1, 2, 3, 4].forEach((w, i) => {
  const pts = {}; raw(w).forEach(m => pts['s' + m.roster_id] = Math.round(m.points * 100) / 100);
  games[i].forEach(g => { if (w < 4 && (Math.abs(g[1] - pts[g[0]]) > 0.01 || Math.abs(g[3] - pts[g[2]]) > 0.01)) { allMatch = false; console.log('   mismatch wk', w, g, pts[g[0]], pts[g[2]]); } });
  console.log('   week', w, JSON.stringify(games[i]));
});
ok('weeks 1-3: every team score is Sleeper\'s', allMatch);
const pair = raw(4), mine = pair.find(m => m.roster_id === 1), opp = pair.find(m => m.matchup_id === mine.matchup_id && m.roster_id !== 1);
const lt = await p.evaluate(`lvState().LT`);
console.log('live matchup', JSON.stringify(lt), 'sleeper', mine.points, opp.points);
ok('week 4 live score equals Sleeper\'s', Math.abs(lt.a - mine.points) < 0.15 && Math.abs(lt.x - opp.points) < 0.15);
const ro = await p.evaluate(`(() => { const r = rosterOf(MY_TEAM_KEY()); return null; })()`).catch(() => null);
const roster = await p.evaluate(`(() => { const k = myLeagues().find(l => l.sleeper).teams[0].key; const r = rosterOf(k); return { starters: r.starters.map(s => s.slot + ':' + (s.player ? s.player.n : '-')), bench: r.bench.filter(Boolean).length, taxi: r.taxi.filter(Boolean).map(x => x.n), ir: r.ir.filter(Boolean).map(x => x.n) }; })()`);
console.log(JSON.stringify(roster));
const rr = JSON.parse(fs.readFileSync(R + 'league/rosters.json')).find(x => x.roster_id === 1);
ok('roster sizes match Sleeper', roster.bench + roster.taxi.length + roster.ir.length + roster.starters.filter(s => !/-$/.test(s)).length === rr.players.length, `${rr.players.length} players`);
const um = await p.evaluate(() => { const r = myLeagues().find(l => l.sleeper); let n = 0; const miss = []; r.teams.forEach(t => { const ro = rosterOf(t.key); [ro.starters.map(x => x.player), ro.bench, ro.taxi, ro.ir].forEach(a => a.forEach(pl => { if (!pl) return; n++; if (String(pl.id).startsWith('sl:')) miss.push(pl.full + ' ' + pl.pos + ' ' + pl.tm); })); }); return { n, miss }; });
ok(`players linked to the app: ${um.n - um.miss.length}/${um.n}`, um.miss.length <= um.n * 0.03, um.miss.join(', '));
await p.evaluate(`showView('matchup'); renderUserMatchup()`); await p.waitForTimeout(500);
await p.screenshot({ path: OUT + '/S2-matchup.png' });
await p.evaluate(`showTab('standings')`).catch(() => {}); await p.waitForTimeout(500);
await p.screenshot({ path: OUT + '/S3-league.png' });
console.log('sleeper requests', JSON.stringify(hits));
console.log('errors:', errs.length ? errs : 'none');
await b.close();
